# Generated by Django 4.0.5 on 2022-06-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfPokemonNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
            ],
        ),
    ]
