# Generated by Django 4.0.5 on 2022-06-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_tableofpokemonnames_evolution_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('names', models.CharField(max_length=100, unique=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
        migrations.DeleteModel(
            name='TableOfPokemonNames',
        ),
    ]
